import type { productTable, subcategoryTable } from "./schema/catalog/tables";

type ProductInsert = typeof productTable.$inferInsert;
type SubcategoryInsert = typeof subcategoryTable.$inferInsert;

const IMAGE_POOL = [
  "photo-1508962914676-134849a727f0",
  "photo-1533139502658-0198f920d8e8",
  "photo-1524592094714-0f0654e20314",
  "photo-1582043568773-a7a2b57239f5",
  "photo-1605143185650-77944b152643",
  "photo-1524805444758-089113d48a6d",
  "photo-1523170335258-f5ed11844a49",
  "photo-1547996160-81dfa63595aa",
  "photo-1522312346375-d1a52e2b99b3",
  "photo-1551024506-0bccd828d307",
  "photo-1579586337278-3befd40fd17a",
  "photo-1594534475808-b18fc33b045e",
  "photo-1587836374828-4dbafa94cf0e",
  "photo-1614164185128-e4ec99c436d7",
  "photo-1622434641406-a158123450f9",
  "photo-1525966222134-fcfa99b8ae77",
  "photo-1434056886845-dac89ffe9b56",
  "photo-1548171915-e79a38a136a9",
];

function img(index: number): string {
  return `https://images.unsplash.com/${IMAGE_POOL[index % IMAGE_POOL.length]}?w=1200&auto=format&fit=crop&q=80`;
}

export const watchBrandSubcategories: SubcategoryInsert[] = [
  { categoryId: "timepieces", id: "patek-philippe", name: "Patek Philippe", slug: "patek-philippe", sortOrder: 0 },
  { categoryId: "timepieces", id: "tudor", name: "Tudor", slug: "tudor", sortOrder: 1 },
  { categoryId: "timepieces", id: "omega", name: "Omega", slug: "omega", sortOrder: 2 },
  { categoryId: "timepieces", id: "vacheron-constantin", name: "Vacheron Constantin", slug: "vacheron-constantin", sortOrder: 3 },
  { categoryId: "timepieces", id: "cartier", name: "Cartier", slug: "cartier", sortOrder: 4 },
  { categoryId: "timepieces", id: "richard-mille", name: "Richard Mille", slug: "richard-mille", sortOrder: 5 },
  { categoryId: "timepieces", id: "breitling", name: "Breitling", slug: "breitling", sortOrder: 6 },
  { categoryId: "timepieces", id: "audemars-piguet", name: "Audemars Piguet", slug: "audemars-piguet", sortOrder: 7 },
  { categoryId: "timepieces", id: "jaeger-lecoultre", name: "Jaeger-LeCoultre", slug: "jaeger-lecoultre", sortOrder: 8 },
  { categoryId: "timepieces", id: "breguet", name: "Breguet", slug: "breguet", sortOrder: 9 },
  { categoryId: "timepieces", id: "piaget", name: "Piaget", slug: "piaget", sortOrder: 10 },
  { categoryId: "timepieces", id: "chopard", name: "Chopard L.U.C", slug: "chopard", sortOrder: 11 },
  { categoryId: "timepieces", id: "hublot", name: "Hublot", slug: "hublot", sortOrder: 12 },
  { categoryId: "timepieces", id: "zenith", name: "Zenith", slug: "zenith", sortOrder: 13 },
  { categoryId: "timepieces", id: "iwc-schaffhausen", name: "IWC Schaffhausen", slug: "iwc-schaffhausen", sortOrder: 14 },
  { categoryId: "timepieces", id: "panerai", name: "Panerai", slug: "panerai", sortOrder: 15 },
  { categoryId: "timepieces", id: "rolex", name: "Rolex", slug: "rolex", sortOrder: 16 },
];

export const watchBrandProducts: ProductInsert[] = [
  // ── Patek Philippe ──────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The original luxury sports watch, with a porthole-inspired case and the horizontally embossed blue dial that made the Nautilus an icon. Calibre 26-330 SC, finished entirely by hand.",
    featured: true,
    features: [
      "Calibre 26-330 SC self-winding movement",
      "Horizontally embossed deep blue dial",
      "Steel bracelet with fold-over clasp",
      "Sapphire crystal, scratch-resistant",
      "Water resistant to 120m",
    ],
    id: "patek-nautilus-5711",
    image: img(0),
    movement: "Automatic",
    name: "Nautilus 5711/1A-010",
    price: 34000,
    ref: "5711/1A-010",
    specs: {
      Case: "40mm, steel",
      Crystal: "Scratch-resistant sapphire, antireflective",
      Movement: "Calibre 26-330 SC, self-winding, 45h reserve",
      Strap: "Steel bracelet, fold-over clasp",
      Warranty: "5-year international movement warranty",
      "Water Resistance": "120m / 12 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "patek-philippe",
    waterResistanceM: 120,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "A sportier, younger sibling to the Nautilus, distinguished by its embossed black dial and the stamped rubber strap that defined an era of luxury casual.",
    featured: false,
    features: [
      "Calibre 26-330 SC self-winding movement",
      "Embossed black dial with applied gold numerals",
      "Tropical rubber strap, adjustable fold-over clasp",
      "Screw-down crown, 120m water resistance",
    ],
    id: "patek-aquanaut-5167",
    image: img(6),
    movement: "Automatic",
    name: "Aquanaut 5167A-001",
    price: 21000,
    ref: "5167A-001",
    specs: {
      Case: "40mm, steel",
      Crystal: "Scratch-resistant sapphire",
      Movement: "Calibre 26-330 SC, self-winding, 45h reserve",
      Strap: "Black tropical rubber, fold-over clasp",
      "Water Resistance": "120m / 12 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "patek-philippe",
    waterResistanceM: 120,
  },
  {
    caseMaterial: "White Gold",
    caseSizeMm: 39,
    categoryId: "timepieces",
    description:
      "The quintessential dress watch. A white gold case, a clean 'Clous de Paris' hobnail bezel, and the hand-wound Calibre 30-255 PS behind a sapphire caseback.",
    featured: false,
    features: [
      "Hand-wound Calibre 30-255 PS, 65h reserve",
      "Clous de Paris hobnail bezel",
      "Sapphire caseback, hand-finished movement",
      "Glossy black alligator strap",
    ],
    id: "patek-calatrava-6119",
    image: img(2),
    movement: "Hand-Wound",
    name: "Calatrava 6119G-001",
    price: 31000,
    ref: "6119G-001",
    specs: {
      Case: "39mm, 18k white gold",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 30-255 PS, hand-wound, 65h reserve",
      Strap: "Black alligator, pin buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "patek-philippe",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "White Gold",
    caseSizeMm: 39,
    categoryId: "timepieces",
    description:
      "A full perpetual calendar with retrograde date, moon phases and leap-year indication, cased in white gold with a dial of hand-guilloché silver. Patek's answer to complexity.",
    featured: false,
    features: [
      "Calibre 240 Q with perpetual calendar, retrograde date, moon phases",
      "Hand-guilloché silver dial",
      "Carré Clous de Paris case-band detail",
      "Sapphire caseback showing the micro-rotor",
    ],
    id: "patek-grand-complications-5327",
    image: img(7),
    movement: "Automatic",
    name: "Grand Complications 5327G-001",
    price: 100000,
    ref: "5327G-001",
    specs: {
      Case: "39mm, 18k white gold",
      Crystal: "Camphor, front and back",
      Movement: "Calibre 240 Q, self-winding micro-rotor",
      Strap: "Dark brown alligator",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "patek-philippe",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 36,
    categoryId: "timepieces",
    description:
      "A round automatic with a subtle grey dial set with applied diamond indices, on a steel bracelet. Understated luxury engineered for everyday wear.",
    featured: false,
    features: [
      "Calibre 324 S C self-winding movement",
      "Grey dial with applied diamond indices",
      "Steel bracelet with fold-over clasp",
      "Sapphire crystal, front and back",
    ],
    id: "patek-twenty4-7300",
    image: img(5),
    movement: "Automatic",
    name: "Twenty~4 Automatic 7300/1200A-011",
    price: 35000,
    ref: "7300/1200A-011",
    specs: {
      Case: "36mm, steel",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 324 S C, self-winding, 45h reserve",
      Strap: "Steel bracelet, fold-over clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "patek-philippe",
    waterResistanceM: 30,
  },

  // ── Tudor ───────────────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 39,
    categoryId: "timepieces",
    description:
      "The 1958-sized dive watch: a 39mm case with a gilt-domed dial and riveted-style bracelet, powered by the METAS-grade Calibre MT5402.",
    featured: true,
    features: [
      "Calibre MT5402, COSC-certified, 70h reserve",
      "39mm case, retro-inspired domed dial",
      "Screw-down crown, 200m water resistance",
      "Steel bracelet with T-fit clasp",
    ],
    id: "tudor-black-bay-58",
    image: img(8),
    movement: "Automatic",
    name: "Black Bay Fifty-Eight M79030N",
    price: 4000,
    ref: "M79030N-0001",
    specs: {
      Case: "39mm, steel",
      Crystal: "Domed sapphire",
      Movement: "Calibre MT5402, self-winding, 70h reserve",
      Strap: "Steel bracelet, T-fit clasp",
      "Water Resistance": "200m / 20 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "tudor",
    waterResistanceM: 200,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A column-wheel chronograph with a tachymeter bezel and the iconic 'snowflake' hands, combining the Black Bay's dive pedigree with a racing soul.",
    featured: false,
    features: [
      "Calibre MT5813 column-wheel chronograph, 70h reserve",
      "Tachymetric fixed bezel in steel",
      "Snowflake hands and domed matte dial",
      "Screw-down pushers, 200m water resistance",
    ],
    id: "tudor-black-bay-chrono",
    image: img(3),
    movement: "Automatic",
    name: "Black Bay Chrono M79360N",
    price: 5700,
    ref: "M79360N-0001",
    specs: {
      Case: "41mm, steel",
      Crystal: "Domed sapphire",
      Movement: "Calibre MT5813, column-wheel chronograph, 70h reserve",
      Strap: "Steel bracelet, T-fit clasp",
      "Water Resistance": "200m / 20 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "tudor",
    waterResistanceM: 200,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 39,
    categoryId: "timepieces",
    description:
      "An expedition tool watch born of the 1952 British North Greenland expedition, with luminous 3-6-9 Arabic numerals and a rugged flat-brushed bracelet.",
    featured: false,
    features: [
      "Calibre MT5402, 70h power reserve",
      "Ochre-accented 3-6-9 dial with full lume",
      "Flat-brushed steel bracelet",
      "Screw-down crown, 100m water resistance",
    ],
    id: "tudor-ranger",
    image: img(1),
    movement: "Automatic",
    name: "Ranger M79950",
    price: 3200,
    ref: "M79950-0001",
    specs: {
      Case: "39mm, steel",
      Crystal: "Flat sapphire",
      Movement: "Calibre MT5402, self-winding, 70h reserve",
      Strap: "Steel bracelet, clasp with micro-adjust",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "tudor",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Titanium",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "A professional-grade dive tool in matte titanium with a helium escape valve, rated to 500 metres and fitted with a self-adjusting clasp.",
    featured: false,
    features: [
      "Calibre MT5612, 70h reserve",
      "Titanium case, 500m water resistance",
      "Helium escape valve, blue luminous markers",
      "Steel-titanium bracelet with self-adjusting clasp",
    ],
    id: "tudor-pelagos",
    image: img(10),
    movement: "Automatic",
    name: "Pelagos M25600TN",
    price: 5000,
    ref: "M25600TN-0001",
    specs: {
      Case: "42mm, titanium",
      Crystal: "Sapphire",
      Movement: "Calibre MT5612, self-winding, 70h reserve",
      Strap: "Titanium bracelet, self-adjusting clasp",
      "Water Resistance": "500m / 50 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "tudor",
    waterResistanceM: 500,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 37,
    categoryId: "timepieces",
    description:
      "Inspired by the first Tudor dive watch of 1954, the Fifty-Four shrinks the Black Bay to 37mm with a deep navy dial and matte case.",
    featured: false,
    features: [
      "Calibre MT5400, 70h power reserve",
      "37mm case inspired by the 1954 Submariner",
      "Screw-down crown, 200m water resistance",
      "Steel bracelet with T-fit clasp",
    ],
    id: "tudor-black-bay-54",
    image: img(9),
    movement: "Automatic",
    name: "Black Bay Fifty-Four M79000N",
    price: 4000,
    ref: "M79000N-0001",
    specs: {
      Case: "37mm, steel",
      Crystal: "Domed sapphire",
      Movement: "Calibre MT5400, self-winding, 70h reserve",
      Strap: "Steel bracelet, T-fit clasp",
      "Water Resistance": "200m / 20 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "tudor",
    waterResistanceM: 200,
  },

  // ── Omega ───────────────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "The chronograph worn on the Moon. A black step dial, Hesalite crystal and hand-wound Co-Axial Master Chronometer calibre 3861 keep the legend ticking.",
    featured: true,
    features: [
      "Calibre 3861, Master Chronometer certified",
      "Black step dial, tachymeter bezel",
      "Hesalite crystal with iconic dome",
      "Steel bracelet, 50m water resistance",
    ],
    id: "omega-speedmaster-moonwatch",
    image: img(11),
    movement: "Manual-Wind",
    name: "Speedmaster Moonwatch Professional",
    price: 7000,
    ref: "310.30.42.50.01.001",
    specs: {
      Case: "42mm, steel",
      Crystal: "Hesalite, domed",
      Movement: "Calibre 3861, hand-wound, 50h reserve",
      Strap: "Steel bracelet, fold-over clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "omega",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "James Bond's watch: a ceramic wave-pattern dial and ceramic bezel on steel, driven by the anti-magnetic Master Chronometer calibre 8800.",
    featured: false,
    features: [
      "Calibre 8800, Master Chronometer certified",
      "Ceramic wave-pattern dial and bezel",
      "Helium escape valve, 300m water resistance",
      "Steel bracelet with fold-over clasp",
    ],
    id: "omega-seamaster-diver-300m",
    image: img(12),
    movement: "Automatic",
    name: "Seamaster Diver 300M",
    price: 5400,
    ref: "210.30.42.20.03.001",
    specs: {
      Case: "42mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 8800, self-winding, 55h reserve",
      Strap: "Steel bracelet, fold-over clasp",
      "Water Resistance": "300m / 30 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "omega",
    waterResistanceM: 300,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A go-anywhere sport watch with the signature teak-deck horizontal dial, Master Chronometer precision and a sapphire exhibition caseback.",
    featured: false,
    features: [
      "Calibre 8900, Master Chronometer certified",
      "Teak-deck concept dial",
      "Sapphire caseback, 60h power reserve",
      "150m water resistance",
    ],
    id: "omega-aqua-terra-150m",
    image: img(13),
    movement: "Automatic",
    name: "Seamaster Aqua Terra 150M",
    price: 6000,
    ref: "220.10.41.21.03.001",
    specs: {
      Case: "41mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 8900, self-winding, 60h reserve",
      Strap: "Steel bracelet, fold-over clasp",
      "Water Resistance": "150m / 15 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "omega",
    waterResistanceM: 150,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A vintage-inspired reissue of the original 1957 'Broad Arrow' Speedmaster, powered by the integrated chronograph calibre 9906 with a 60-hour reserve.",
    featured: false,
    features: [
      "Calibre 9906, Master Chronometer certified",
      "Broad Arrow hands, brushed 'First Omega in Space' dial",
      "60h power reserve, anti-magnetic to 15,000 gauss",
      "Steel bracelet, 50m water resistance",
    ],
    id: "omega-speedmaster-57",
    image: img(14),
    movement: "Automatic",
    name: "Speedmaster '57",
    price: 8400,
    ref: "332.10.41.51.01.001",
    specs: {
      Case: "40.5mm, steel",
      Crystal: "Domed sapphire",
      Movement: "Calibre 9906, self-winding, 60h reserve",
      Strap: "Steel bracelet, fold-over clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "omega",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "The 'Côtes de Genève' dial and star-studded bezel define this 1952 icon, now fitted with the anti-magnetic calibre 8900 and an integrated bracelet.",
    featured: false,
    features: [
      "Calibre 8900, Master Chronometer certified",
      "Clous de Paris / Côtes de Genève dial",
      "Star-studded bezel, integrated bracelet",
      "50m water resistance",
    ],
    id: "omega-constellation",
    image: img(15),
    movement: "Automatic",
    name: "Constellation 41",
    price: 5600,
    ref: "131.30.41.21.01.001",
    specs: {
      Case: "41mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 8900, self-winding, 60h reserve",
      Strap: "Integrated steel bracelet",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "omega",
    waterResistanceM: 50,
  },

  // ── Vacheron Constantin ─────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "The gentleman's sports watch, recognisable by the Maltese-cross bezel, with a quick-change bracelet system and the 22k gold micro-rotor calibre 5100.",
    featured: true,
    features: [
      "Calibre 5100 with 22k gold micro-rotor, 60h reserve",
      "Maltese-cross inspired bezel",
      "Quick-change steel bracelet, strap and rubber",
      "Sapphire caseback, 150m water resistance",
    ],
    id: "vc-overseas-4500",
    image: img(16),
    movement: "Automatic",
    name: "Overseas 4500V/110A-B128",
    price: 23000,
    ref: "4500V/110A-B128",
    specs: {
      Case: "41mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 5100, self-winding, 60h reserve",
      Strap: "Steel bracelet, quick-change system",
      "Water Resistance": "150m / 15 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "vacheron-constantin",
    waterResistanceM: 150,
  },
  {
    caseMaterial: "White Gold",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "A pure expression of minimalism: a white gold case, a bare silvered dial with applied gold indices and a single date, driven by calibre 2450 Q6.",
    featured: false,
    features: [
      "Calibre 2450 Q6, self-winding, 40h reserve",
      "Silvered dial, applied 18k gold hour markers",
      "Glossy alligator strap, gold pin buckle",
      "Sapphire crystal, front and back",
    ],
    id: "vc-patrimony-85180",
    image: img(2),
    movement: "Automatic",
    name: "Patrimony 85180/000G-9230",
    price: 32000,
    ref: "85180/000G-9230",
    specs: {
      Case: "40mm, 18k white gold",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 2450 Q6, self-winding, 40h reserve",
      Strap: "Dark blue alligator, 18k gold buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "vacheron-constantin",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Rose Gold",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A perpetual calendar in rose gold with retrograde date and moon phase, finished in the meticulous hand-workmanship that defined 18th-century Geneva.",
    featured: false,
    features: [
      "Calibre 2460 QCL/1 with retrograde date",
      "Rose gold case, 'diamanté' stepped bezel",
      "Moon phase and leap-year indication",
      "Hand-stitched alligator strap",
    ],
    id: "vc-traditionnelle-43175",
    image: img(7),
    movement: "Automatic",
    name: "Traditionnelle Perpetual Calendar",
    price: 80000,
    ref: "43175/000R-B219",
    specs: {
      Case: "41mm, 18k rose gold",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 2460 QCL/1, self-winding, 40h reserve",
      Strap: "Hand-stitched alligator, 18k gold buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "vacheron-constantin",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "Inspired by a 1956 Vacheron, the FiftySix merges a sector dial with a stainless case and an integrated crown-logo, powered by calibre 1326.",
    featured: false,
    features: [
      "Calibre 1326, self-winding, 38h reserve",
      "Sector dial with vintage numerals",
      "Maltese-cross half-inertia oscillating weight",
      "Steel bracelet with easy-to-change straps",
    ],
    id: "vc-fiftysix-4600",
    image: img(6),
    movement: "Automatic",
    name: "FiftySix 4600E/000A-B442",
    price: 12000,
    ref: "4600E/000A-B442",
    specs: {
      Case: "40mm, steel",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 1326, self-winding, 38h reserve",
      Strap: "Steel bracelet, quick-change",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "vacheron-constantin",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "White Gold",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "A 100-year-old design: the case is rotated 45° and the crown sits at 1 o'clock, so the driver reads the time without lifting his hand from the wheel.",
    featured: false,
    features: [
      "Calibre 4400 AS, hand-wound, 65h reserve",
      "Diagonal crown, tilted dial design",
      "18k white gold case, 100-piece run",
      "Openworked winding crown",
    ],
    id: "vc-american-1921",
    image: img(17),
    movement: "Hand-Wound",
    name: "Historiques American 1921",
    price: 36000,
    ref: "82035/000G-9359",
    specs: {
      Case: "40mm, 18k white gold",
      Crystal: "Domed sapphire",
      Movement: "Calibre 4400 AS, hand-wound, 65h reserve",
      Strap: "Dark brown alligator, 18k gold buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "vacheron-constantin",
    waterResistanceM: 30,
  },

  // ── Cartier ─────────────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The first modern pilot's watch, built for Alberto Santos-Dumont in 1904. Screw-in bezel, exposed screws and the signature square case on a steel bracelet.",
    featured: true,
    features: [
      "Calibre 1847 MC, self-winding, 42h reserve",
      "Square case with exposed screws",
      "Quick-switch steel bracelet and strap",
      "100m water resistance",
    ],
    id: "cartier-santos-wssa0009",
    image: img(0),
    movement: "Automatic",
    name: "Santos de Cartier WSSA0009",
    price: 7000,
    ref: "WSSA0009",
    specs: {
      Case: "39.8mm, steel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 1847 MC, self-winding, 42h reserve",
      Strap: "Steel bracelet, quick-switch",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "cartier",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Yellow Gold",
    caseSizeMm: 34,
    categoryId: "timepieces",
    description:
      "The timeless 'tank' seen on wrists from Jackie O to Andy Warhol. A yellow gold case, Roman numerals, and a hand-wound mechanical calibre 1917 MC.",
    featured: false,
    features: [
      "Hand-wound calibre 1917 MC, 38h reserve",
      "18k yellow gold case, Roman numerals",
      "Blue-steel sword hands",
      "Alligator strap with gold ardillon buckle",
    ],
    id: "cartier-tank-louis",
    image: img(1),
    movement: "Hand-Wound",
    name: "Tank Louis Cartier WGTA0011",
    price: 12000,
    ref: "WGTA0011",
    specs: {
      Case: "33.7mm, 18k yellow gold",
      Crystal: "Sapphire",
      Movement: "Calibre 1917 MC, hand-wound, 38h reserve",
      Strap: "Black alligator, gold ardillon buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "cartier",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "A round watch with a distinctive crown guard and a cabochon-topped winding crown, floating Roman numerals on a silvered guilloché dial.",
    featured: false,
    features: [
      "Calibre 1847 MC, self-winding, 42h reserve",
      "Floating Roman numerals, flinqué dial",
      "Cabochon-set winding crown",
      "Steel bracelet with folding clasp",
    ],
    id: "cartier-ballon-bleu-wsbb0043",
    image: img(8),
    movement: "Automatic",
    name: "Ballon Bleu de Cartier WSBB0043",
    price: 7500,
    ref: "WSBB0043",
    specs: {
      Case: "42mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre 1847 MC, self-winding, 42h reserve",
      Strap: "Steel bracelet, folding clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "cartier",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 30,
    categoryId: "timepieces",
    description:
      "Feline and geometric, the Panthère returns in a small steel case on a flexible hexagonal bracelet — a faithful reissue of the 1980s icon.",
    featured: false,
    features: [
      "Quartz calibre 157, 8-year battery life",
      "Hexagonal links, flexible bracelet",
      "Clou de Paris dial, Roman numerals",
      "30m water resistance",
    ],
    id: "cartier-panthere-w2pn0006",
    image: img(9),
    movement: "Quartz",
    name: "Panthère de Cartier W2PN0006",
    price: 4300,
    ref: "W2PN0006",
    specs: {
      Case: "30mm, steel",
      Crystal: "Sapphire",
      Movement: "Quartz calibre 157",
      Strap: "Steel hexagonal bracelet",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "cartier",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Rose Gold",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "A slim dress watch in rose gold with a silvered guilloché dial, hand-wound calibre 430 MC and a crown set with a blue cabochon.",
    featured: false,
    features: [
      "Hand-wound calibre 430 MC, 40h reserve",
      "Silvered guilloché dial",
      "18k rose gold case, blue cabochon crown",
      "Alligator strap with gold buckle",
    ],
    id: "cartier-ronde-wsrn0017",
    image: img(5),
    movement: "Hand-Wound",
    name: "Ronde Louis Cartier WSRN0017",
    price: 9000,
    ref: "WSRN0017",
    specs: {
      Case: "40mm, 18k rose gold",
      Crystal: "Sapphire",
      Movement: "Calibre 430 MC, hand-wound, 40h reserve",
      Strap: "Brown alligator, gold buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "cartier",
    waterResistanceM: 30,
  },

  // ── Richard Mille ───────────────────────────────────────────────────────────
  {
    caseMaterial: "Titanium",
    caseSizeMm: 50,
    categoryId: "timepieces",
    description:
      "A tonneau flyback chronograph with annual calendar, built for a Formula One driver. Titanium case, sapphire dial, and a skeletonised automatic calibre RMAC1.",
    featured: true,
    features: [
      "Skeletonised automatic calibre RMAC1",
      "Flyback chronograph, annual calendar",
      "Titanium tonneau case",
      "Variable-geometry rotor",
    ],
    id: "rm-011-felipe-massa",
    image: img(3),
    movement: "Automatic",
    name: "RM 011 Felipe Massa",
    price: 150000,
    ref: "RM011-FM",
    specs: {
      Case: "50 x 40mm, titanium",
      Crystal: "Sapphire, glareproofed",
      Movement: "RMAC1, self-winding, 55h reserve",
      Strap: "Rubber, titanium buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "richard-mille",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Titanium",
    caseSizeMm: 43,
    categoryId: "timepieces",
    description:
      "Developed in partnership with a tennis champion, this ultra-light automatic is cased in high-performance quartz-TPT and titanium for near-zero mass.",
    featured: false,
    features: [
      "Skeletonised automatic calibre RMAC3",
      "Quartz TPT and titanium case",
      "Baseplate of grade 5 titanium",
      "Variable-inertia balance, 55h reserve",
    ],
    id: "rm-035",
    image: img(10),
    movement: "Automatic",
    name: "RM 035 Rafael Nadal",
    price: 250000,
    ref: "RM035",
    specs: {
      Case: "43mm, quartz TPT and titanium",
      Crystal: "Sapphire, glareproofed",
      Movement: "Skeletonised automatic, 55h reserve",
      Strap: "Rubber, titanium buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "richard-mille",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Titanium",
    caseSizeMm: 47,
    categoryId: "timepieces",
    description:
      "Richard Mille's answer to the dive watch: a rotating bezel operated by a crown-integrated pusher, rated to 300 metres in a lightweight titanium case.",
    featured: false,
    features: [
      "Automatic calibre RMAS7, 55h reserve",
      "Diver's bezel with crown-actuated lock",
      "Titanium case, 300m water resistance",
      "Torque-limiting crown",
    ],
    id: "rm-028-diver",
    image: img(12),
    movement: "Automatic",
    name: "RM 028 Diver",
    price: 145000,
    ref: "RM028",
    specs: {
      Case: "47mm, titanium",
      Crystal: "Sapphire, glareproofed",
      Movement: "Automatic calibre RMAS7, 55h reserve",
      Strap: "Rubber, titanium buckle",
      "Water Resistance": "300m / 30 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "richard-mille",
    waterResistanceM: 300,
  },
  {
    caseMaterial: "Gold",
    caseSizeMm: 48,
    categoryId: "timepieces",
    description:
      "An extra-flat dress Richard Mille in 18k gold with a skeletonised automatic movement and a hand-stitched alligator strap — rarity as much as engineering.",
    featured: false,
    features: [
      "Extra-flat automatic calibre CRMA6",
      "18k gold case, hand-engraved",
      "Skeletonised dial with gold indices",
      "Alligator strap with gold folding buckle",
    ],
    id: "rm-067-01",
    image: img(7),
    movement: "Automatic",
    name: "RM 067-01 Extra-Flat Automatic",
    price: 500000,
    ref: "RM067-01",
    specs: {
      Case: "47.7mm, 18k gold",
      Crystal: "Sapphire, glareproofed",
      Movement: "Extra-flat automatic CRMA6",
      Strap: "Alligator, gold folding buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "richard-mille",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Carbon",
    caseSizeMm: 50,
    categoryId: "timepieces",
    description:
      "Engineered for a professional golfer, this carbon TPT and quartz TPT chronograph weighs a featherweight and absorbs shock on the course.",
    featured: false,
    features: [
      "Skeletonised automatic calibre RMAC2",
      "Carbon TPT and quartz TPT case",
      "Shock-resistant movement mounting",
      "55h power reserve",
    ],
    id: "rm-055-bubba-watson",
    image: img(14),
    movement: "Automatic",
    name: "RM 055 Bubba Watson",
    price: 185000,
    ref: "RM055",
    specs: {
      Case: "50mm, carbon and quartz TPT",
      Crystal: "Sapphire, glareproofed",
      Movement: "Skeletonised automatic RMAC2",
      Strap: "Rubber, titanium buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "richard-mille",
    waterResistanceM: 50,
  },

  // ── Breitling ───────────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 43,
    categoryId: "timepieces",
    description:
      "The pilot's flight computer par excellence — a circular slide rule, a column-wheel chronograph calibre B01 and a dial engineered for the cockpit.",
    featured: true,
    features: [
      "Breitling calibre B01, 70h reserve",
      "Circular slide rule bezel",
      "Column-wheel chronograph, column of seconds",
      "Black alligator strap",
    ],
    id: "breitling-navitimer-b01",
    image: img(15),
    movement: "Automatic",
    name: "Navitimer B01 Chronograph 43",
    price: 8900,
    ref: "AB0138211B1P1",
    specs: {
      Case: "43mm, steel",
      Crystal: "Camphor sapphire, glareproofed",
      Movement: "Calibre B01, self-winding, 70h reserve",
      Strap: "Black alligator, folding clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "breitling",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "The 1983 Chronomat returns with its rider-tab bezel and onion pushers, powered by the in-house column-wheel calibre B01 with a 70-hour reserve.",
    featured: false,
    features: [
      "Breitling calibre B01, 70h reserve",
      "Rider-tab bezel, onion crown and pushers",
      "Three-row steel bracelet",
      "200m water resistance",
    ],
    id: "breitling-chronomat-b01",
    image: img(4),
    movement: "Automatic",
    name: "Chronomat B01 42",
    price: 8400,
    ref: "AB0118A21B1A1",
    specs: {
      Case: "42mm, steel",
      Crystal: "Camphor sapphire, glareproofed",
      Movement: "Calibre B01, self-winding, 70h reserve",
      Strap: "Steel bracelet, folding clasp",
      "Water Resistance": "200m / 20 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "breitling",
    waterResistanceM: 200,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "A mid-century dive watch reissue with a 42mm slim case, a concave bezel and a dark blue dial on a 'brown-on-beige' leather strap.",
    featured: false,
    features: [
      "Breitling calibre B20 (based on Tudor MT5612), 70h reserve",
      "Concave rotating bezel",
      "Bombe lugs, 42mm slim case",
      "100m water resistance",
    ],
    id: "breitling-superocean-heritage-57",
    image: img(11),
    movement: "Automatic",
    name: "Superocean Heritage '57",
    price: 7000,
    ref: "AB2030121B1A1",
    specs: {
      Case: "42mm, steel",
      Crystal: "Camphor sapphire, glareproofed",
      Movement: "Calibre B20, self-winding, 70h reserve",
      Strap: "Leather, pin buckle",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "breitling",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 45,
    categoryId: "timepieces",
    description:
      "Built for the cockpit of a fighter jet: a 45mm case, unidirectional bezel, chronograph pushers and 300-metre water resistance with a clear calendar.",
    featured: false,
    features: [
      "Breitling calibre B01, 70h reserve",
      "Unidirectional rotating bezel",
      "Grenade-textured dial",
      "300m water resistance, chronometer certified",
    ],
    id: "breitling-avenger-b01-45",
    image: img(13),
    movement: "Automatic",
    name: "Avenger B01 Chronograph 45",
    price: 8500,
    ref: "AB0110121C1A1",
    specs: {
      Case: "45mm, steel",
      Crystal: "Camphor sapphire, glareproofed",
      Movement: "Calibre B01, self-winding, 70h reserve",
      Strap: "Steel bracelet, folding clasp",
      "Water Resistance": "300m / 30 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "breitling",
    waterResistanceM: 300,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "A dress chronograph with a hand-wound, column-wheel calibre B09, a silvered dial with applied indices and a vintage-inspired polished case.",
    featured: false,
    features: [
      "Hand-wound calibre B09, 70h reserve",
      "Column-wheel chronograph",
      "Silvered dial, applied indices",
      "100m water resistance",
    ],
    id: "breitling-premier-b09",
    image: img(17),
    movement: "Manual-Wind",
    name: "Premier B09 Chronograph 40",
    price: 8900,
    ref: "AB0910171K1P1",
    specs: {
      Case: "40mm, steel",
      Crystal: "Camphor sapphire, glareproofed",
      Movement: "Calibre B09, hand-wound, 70h reserve",
      Strap: "Black alligator, pin buckle",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "breitling",
    waterResistanceM: 100,
  },

  // ── Audemars Piguet ─────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "The 1972 Gérald Genta icon in 41mm steel — an octagonal bezel with visible screws and the 'Grande Tapisserie' dial over calibre 4302.",
    featured: true,
    features: [
      "Calibre 4302, self-winding, 70h reserve",
      "Octagonal bezel with visible screws",
      "Grande Tapisserie dial",
      "Integrated steel bracelet",
    ],
    id: "ap-royal-oak-15500",
    image: img(16),
    movement: "Automatic",
    name: "Royal Oak 15500ST",
    price: 25000,
    ref: "15500ST.OO.1220ST.01",
    specs: {
      Case: "41mm, steel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 4302, self-winding, 70h reserve",
      Strap: "Integrated steel bracelet, AP clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "audemars-piguet",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 39,
    categoryId: "timepieces",
    description:
      "The true heir to the 1972 original: 39mm, a 'Petite Tapisserie' blue dial, ultra-thin calibre 7121 and the legendary integrated bracelet.",
    featured: false,
    features: [
      "Ultra-thin calibre 7121, 55h reserve",
      "Petite Tapisserie blue dial",
      "39mm case, original proportions",
      "Ultra-thin, integrated steel bracelet",
    ],
    id: "ap-royal-oak-jumbo-16202",
    image: img(0),
    movement: "Automatic",
    name: "Royal Oak 'Jumbo' 16202ST",
    price: 35000,
    ref: "16202ST.OO.1240ST.01",
    specs: {
      Case: "39mm, steel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 7121, self-winding, 55h reserve",
      Strap: "Integrated steel bracelet, AP clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "audemars-piguet",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A flyback chronograph Royal Oak with an integrated column-wheel calibre 4401 and a gradient blue 'Grande Tapisserie' dial.",
    featured: false,
    features: [
      "Flyback calibre 4401, column-wheel, 70h reserve",
      "Gradient blue Grande Tapisserie dial",
      "Integrated steel bracelet",
      "50m water resistance",
    ],
    id: "ap-royal-oak-chrono-26240",
    image: img(3),
    movement: "Automatic",
    name: "Royal Oak Chronograph 26240ST",
    price: 32000,
    ref: "26240ST.OO.1320ST.01",
    specs: {
      Case: "41mm, steel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 4401, self-winding, 70h reserve",
      Strap: "Integrated steel bracelet, AP clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "audemars-piguet",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "The bigger, bolder 1993 'Beast': 42mm, a 'Méga Tapisserie' dial, rubber-clad chronograph pushers and a contrast stitch rubber strap.",
    featured: false,
    features: [
      "Calibre 3126/3840, self-winding, 50h reserve",
      "Méga Tapisserie dial",
      "Rubber-clad push-pieces and crown",
      "100m water resistance",
    ],
    id: "ap-royal-oak-offshore-26470",
    image: img(10),
    movement: "Automatic",
    name: "Royal Oak Offshore 26470ST",
    price: 25000,
    ref: "26470ST.OO.A027CA.01",
    specs: {
      Case: "42mm, steel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 3126/3840, self-winding, 50h reserve",
      Strap: "Rubber, steel pin buckle",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "audemars-piguet",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A round case with a contoured octagonal bezel and a smoked lacquered dial, powered by the integrated flyback chronograph calibre 4401.",
    featured: false,
    features: [
      "Flyback calibre 4401, column-wheel, 70h reserve",
      "Double-curved sapphire crystal",
      "Smoked lacquered dial",
      "Alligator strap, quick-change",
    ],
    id: "ap-code-1159-26393",
    image: img(2),
    movement: "Automatic",
    name: "Code 11.59 26393ST",
    price: 24000,
    ref: "26393ST.OO.A216CR.01",
    specs: {
      Case: "41mm, steel",
      Crystal: "Double-curved sapphire",
      Movement: "Calibre 4401, self-winding, 70h reserve",
      Strap: "Black alligator, pin buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "audemars-piguet",
    waterResistanceM: 50,
  },

  // ── Jaeger-LeCoultre ────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The 1931 Art Deco icon that flips to protect its dial — now with a small seconds and a reversible case, hand-finished in Le Sentier.",
    featured: true,
    features: [
      "Hand-wound calibre 822/2, 42h reserve",
      "Reversible case with engraved caseback",
      "Sunray-brushed silvered dial",
      "Crocodile strap with strap-changing system",
    ],
    id: "jlc-reverso-classic",
    image: img(1),
    movement: "Manual-Wind",
    name: "Reverso Classic Small Seconds",
    price: 8000,
    ref: "Q2708430",
    specs: {
      Case: "40.1 x 24.4mm, steel, reversible",
      Crystal: "Sapphire",
      Movement: "Calibre 822/2, hand-wound, 42h reserve",
      Strap: "Crocodile, pin buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "jaeger-lecoultre",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 50,
    categoryId: "timepieces",
    description:
      "The Reverso's second face reveals a celestial complication: a deep blue night sky with moon phase and star map around an off-centre dial.",
    featured: false,
    features: [
      "Hand-wound calibre 925/2, 42h reserve",
      "Reversible case, moon phase on the reverse",
      "Silvered dial, blue night sky caseback",
      "Crocodile strap, double folding clasp",
    ],
    id: "jlc-reverso-tribute-moon",
    image: img(17),
    movement: "Manual-Wind",
    name: "Reverso Tribute Moon",
    price: 13000,
    ref: "Q3872560",
    specs: {
      Case: "49.7 x 29.9mm, steel, reversible",
      Crystal: "Sapphire",
      Movement: "Calibre 925/2, hand-wound, 42h reserve",
      Strap: "Crocodile, double folding clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "jaeger-lecoultre",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 39,
    categoryId: "timepieces",
    description:
      "An 39mm, 10.04mm-thin dress watch with moon phase and date, powered by the automatic calibre 925 with a 70-hour reserve.",
    featured: false,
    features: [
      "Calibre 925, self-winding, 70h reserve",
      "Silvered opaline dial, moon phase at 6",
      "10.04mm ultra-thin case",
      "50m water resistance",
    ],
    id: "jlc-master-ultra-thin-moon",
    image: img(8),
    movement: "Automatic",
    name: "Master Ultra Thin Moon",
    price: 9500,
    ref: "Q1362520",
    specs: {
      Case: "39mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre 925, self-winding, 70h reserve",
      Strap: "Alligator, pin buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "jaeger-lecoultre",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "A column-wheel chronograph with a triple calendar, tested for a hundred hours by the Master Control programme of 1,000-hour certification.",
    featured: false,
    features: [
      "Calibre 751, self-winding column-wheel chronograph",
      "Triple calendar with month and moon phase",
      "Silvered sector dial",
      "Alligator strap",
    ],
    id: "jlc-master-control-chrono",
    image: img(15),
    movement: "Automatic",
    name: "Master Control Chronograph",
    price: 9000,
    ref: "Q4138420",
    specs: {
      Case: "40mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre 751, self-winding, 65h reserve",
      Strap: "Alligator, pin buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "jaeger-lecoultre",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A modern reissue of the 1968 Polaris dive watch, with a fume-gradient dial and an inner rotating bezel operated by a second crown.",
    featured: false,
    features: [
      "Calibre 899A/1, self-winding, 38h reserve",
      "Inner rotating bezel via crown",
      "Fume-gradient black dial",
      "100m water resistance, open caseback",
    ],
    id: "jlc-polaris-date",
    image: img(11),
    movement: "Automatic",
    name: "Polaris Date",
    price: 8000,
    ref: "Q9018180",
    specs: {
      Case: "41mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 899A/1, self-winding, 38h reserve",
      Strap: "Steel bracelet, pin buckle",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "jaeger-lecoultre",
    waterResistanceM: 100,
  },

  // ── Breguet ─────────────────────────────────────────────────────────────────
  {
    caseMaterial: "White Gold",
    caseSizeMm: 38,
    categoryId: "timepieces",
    description:
      "Breguet's defining dress watch: a grand feu enamel dial, coin-edged case band and Breguet hands, powered by the self-winding calibre 777Q.",
    featured: true,
    features: [
      "Calibre 777Q, self-winding, 55h reserve",
      "Grand feu enamel dial",
      "Coin-edged case band, Breguet hands",
      "Sapphire caseback",
    ],
    id: "breguet-classique-5177",
    image: img(4),
    movement: "Automatic",
    name: "Classique 5177BB/2B/9V6",
    price: 27000,
    ref: "5177BB/2B/9V6",
    specs: {
      Case: "38mm, 18k white gold",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 777Q, self-winding, 55h reserve",
      Strap: "Alligator, gold folding clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "breguet",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Rose Gold",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "An openworked homage to Breguet's 1801 souscription watches, exposing the gear train and a retrograde seconds hand on a rose gold frame.",
    featured: false,
    features: [
      "Calibre 505SR1, self-winding, 50h reserve",
      "Openworked dial, exposed gear train",
      "Retrograde seconds at 6 o'clock",
      "Rose gold case, coin-edged band",
    ],
    id: "breguet-tradition-7097",
    image: img(7),
    movement: "Automatic",
    name: "Tradition 7097BR/G1/9WU",
    price: 38000,
    ref: "7097BR/G1/9WU",
    specs: {
      Case: "40mm, 18k rose gold",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 505SR1, self-winding, 50h reserve",
      Strap: "Alligator, gold folding clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "breguet",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "White Gold",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "Inspired by Breguet's 1815 marine chronometers, this white gold diver combines a guilloché 'wave' dial with a 100-metre-rated rubber strap.",
    featured: false,
    features: [
      "Calibre 777A, self-winding, 55h reserve",
      "Hand-guilloché wave dial",
      "White gold case, unidirectional bezel",
      "Rubber strap, 100m water resistance",
    ],
    id: "breguet-marine-5517",
    image: img(13),
    movement: "Automatic",
    name: "Marine 5517BB/YS/9ZU",
    price: 30000,
    ref: "5517BB/YS/9ZU",
    specs: {
      Case: "40mm, 18k white gold",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 777A, self-winding, 55h reserve",
      Strap: "Rubber, gold pin buckle",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "breguet",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "The heir to Breguet's 1955 aviation chronograph: a flyback calibre 728 with a bidirectional bezel and a matte black dial for the cockpit.",
    featured: false,
    features: [
      "Flyback calibre 728, self-winding, 60h reserve",
      "Bidirectional bezel, flyback function",
      "Matte black dial, luminous hands",
      "100m water resistance",
    ],
    id: "breguet-type-xx-2067",
    image: img(3),
    movement: "Automatic",
    name: "Type XX 2067ST/H2/3WU",
    price: 16000,
    ref: "2067ST/H2/3WU",
    specs: {
      Case: "42mm, steel",
      Crystal: "Camphor sapphire, glareproofed",
      Movement: "Calibre 728, self-winding, 60h reserve",
      Strap: "Leather, steel folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "breguet",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Platinum",
    caseSizeMm: 43,
    categoryId: "timepieces",
    description:
      "A skeletonised minute repeater in a tonneau-shaped platinum case, showcasing Breguet's most intricate hand-finished movement work.",
    featured: false,
    features: [
      "Hand-wound calibre 507 DR skeletonised",
      "Minute repeater, titanium gongs",
      "Platinum tonneau case",
      "Hand-engraved movement plates",
    ],
    id: "breguet-heritage-5497",
    image: img(5),
    movement: "Hand-Wound",
    name: "Héritage 5497PT/11/P9/DD0D",
    price: 90000,
    ref: "5497PT/11/P9/DD0D",
    specs: {
      Case: "42.5mm, platinum, tonneau",
      Crystal: "Sapphire, front and back",
      Movement: "Calibre 507 DR, hand-wound",
      Strap: "Alligator, platinum folding clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "breguet",
    waterResistanceM: 30,
  },

  // ── Piaget ──────────────────────────────────────────────────────────────────
  {
    caseMaterial: "White Gold",
    caseSizeMm: 38,
    categoryId: "timepieces",
    description:
      "The world's thinnest hand-wound watch of its generation — 3.65mm thick — with the movement integrated into the case itself.",
    featured: true,
    features: [
      "Hand-wound calibre 900P, 48h reserve",
      "3.65mm ultra-thin construction",
      "Movement built into the case",
      "Alligator strap, white gold buckle",
    ],
    id: "piaget-altiplano-900p",
    image: img(6),
    movement: "Hand-Wound",
    name: "Altiplano 900P",
    price: 26000,
    ref: "G0A39111",
    specs: {
      Case: "38mm, 18k white gold",
      Crystal: "Sapphire",
      Movement: "Calibre 900P, hand-wound, 48h reserve",
      Strap: "Black alligator, gold buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "piaget",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "Piaget's sporty side: a brushed-and-polished steel case, a horizontally 'gadroon' decorated blue dial and the self-winding calibre 1110P.",
    featured: false,
    features: [
      "Calibre 1110P, self-winding, 50h reserve",
      "Gadroon-decorated blue dial",
      "Brushed and polished steel bracelet",
      "100m water resistance",
    ],
    id: "piaget-polo-s",
    image: img(16),
    movement: "Automatic",
    name: "Polo S",
    price: 15000,
    ref: "G0A41002",
    specs: {
      Case: "42mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 1110P, self-winding, 50h reserve",
      Strap: "Steel bracelet, folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "piaget",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Yellow Gold",
    caseSizeMm: 38,
    categoryId: "timepieces",
    description:
      "The 1979 original returns in solid gold: 38mm, an integrated gold bracelet and a skeletonised calibre 1200P1 barely 2.35mm thin.",
    featured: false,
    features: [
      "Calibre 1200P1, skeletonised, self-winding",
      "18k yellow gold case and bracelet",
      "2.35mm movement thickness",
      "Guilloché dial",
    ],
    id: "piaget-polo-79",
    image: img(2),
    movement: "Automatic",
    name: "Polo 79",
    price: 70000,
    ref: "G0A48001",
    specs: {
      Case: "38mm, 18k yellow gold",
      Crystal: "Sapphire",
      Movement: "Calibre 1200P1, self-winding, 44h reserve",
      Strap: "18k yellow gold bracelet",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Gold",
    subcategoryId: "piaget",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Cobalt",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A record-breaking 2mm-thick watch: the movement is the case, in cobalt, with a dial-free architecture and a fully integrated hand-wound calibre.",
    featured: false,
    features: [
      "Hand-wound calibre 900P-UC, 45h reserve",
      "2mm total thickness",
      "Movement integrated into the cobalt case",
      "Single-bloc construction",
    ],
    id: "piaget-altiplano-ultimate-concept",
    image: img(14),
    movement: "Hand-Wound",
    name: "Altiplano Ultimate Concept",
    price: 400000,
    ref: "G0A48002",
    specs: {
      Case: "41mm, cobalt",
      Crystal: "Sapphire",
      Movement: "Calibre 900P-UC, hand-wound, 45h reserve",
      Strap: "Leather, cobalt pin buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "piaget",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Rose Gold",
    caseSizeMm: 32,
    categoryId: "timepieces",
    description:
      "A gala creation in rose gold with a crystal-set bezel and asymmetric lugs, inspired by the flamboyance of 1970s gala evenings.",
    featured: false,
    features: [
      "Quartz calibre 56P",
      "18k rose gold case and bracelet",
      "Diamond-set bezel",
      "Mother-of-pearl dial",
    ],
    id: "piaget-limelight-gala",
    image: img(9),
    movement: "Quartz",
    name: "Limelight Gala",
    price: 50000,
    ref: "G0A45157",
    specs: {
      Case: "32mm, 18k rose gold",
      Crystal: "Sapphire",
      Movement: "Quartz calibre 56P",
      Strap: "18k rose gold bracelet",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Gold",
    subcategoryId: "piaget",
    waterResistanceM: 30,
  },

  // ── Chopard L.U.C ───────────────────────────────────────────────────────────
  {
    caseMaterial: "Rose Gold",
    caseSizeMm: 37,
    categoryId: "timepieces",
    description:
      "The watch that launched L.U.C in 1996: a micro-rotor-wound calibre with a Geneva-sealed finish and a silvered 'Jabada' dial in rose gold.",
    featured: true,
    features: [
      "Hand-wound calibre L.U.C 96.01-L, 65h reserve",
      "Chronometer (C.O.S.C.) certified",
      "Silvered opaline Jabada dial",
      "Micro-rotor architecture",
    ],
    id: "chopard-luc-1860",
    image: img(4),
    movement: "Manual-Wind",
    name: "L.U.C 1860",
    price: 28000,
    ref: "161926-1001",
    specs: {
      Case: "36.5mm, 18k rose gold",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre L.U.C 96.01-L, hand-wound, 65h reserve",
      Strap: "Alligator, gold pin buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "chopard",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The 'Xtra Thin, Spirit' — a 40mm steel dress watch with a micro-rotor calibre L.U.C 96.13-L and a hand-guilloché silvered dial.",
    featured: false,
    features: [
      "Micro-rotor calibre L.U.C 96.13-L, 65h reserve",
      "7.2mm ultra-thin steel case",
      "Hand-guilloché silvered dial",
      "Chronometer certified",
    ],
    id: "chopard-luc-xps",
    image: img(8),
    movement: "Automatic",
    name: "L.U.C XPS",
    price: 12000,
    ref: "168510-3001",
    specs: {
      Case: "40mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre L.U.C 96.13-L, self-winding, 65h reserve",
      Strap: "Alligator, steel pin buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "chopard",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Titanium",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "A world-time traveller in titanium with a 24-hour flange ring and a second time zone, driven by the dual-barrel calibre L.U.C 01.10-L.",
    featured: false,
    features: [
      "Calibre L.U.C 01.10-L, 60h reserve",
      "Second time zone with day/night indication",
      "Titanium case, 24-hour flange",
      "Quick-swap rubber strap",
    ],
    id: "chopard-luc-gmt-one",
    image: img(10),
    movement: "Automatic",
    name: "L.U.C GMT One",
    price: 18000,
    ref: "161947-5001",
    specs: {
      Case: "42mm, titanium",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre L.U.C 01.10-L, self-winding, 60h reserve",
      Strap: "Rubber, titanium buckle",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "chopard",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Platinum",
    caseSizeMm: 43,
    categoryId: "timepieces",
    description:
      "A minute repeater with a gong and crystal struck in one piece of sapphire, in platinum — the most complex L.U.C movement ever made.",
    featured: false,
    features: [
      "Hand-wound calibre L.U.C 08.01-L",
      "Monobloc sapphire gong and crystal",
      "Platinum case",
      "Guilloché dial, 4Hz regulator",
    ],
    id: "chopard-luc-full-strike",
    image: img(12),
    movement: "Hand-Wound",
    name: "L.U.C Full Strike",
    price: 300000,
    ref: "161947-5002",
    specs: {
      Case: "42.5mm, platinum",
      Crystal: "Sapphire (struck as one piece)",
      Movement: "Calibre L.U.C 08.01-L, hand-wound",
      Strap: "Alligator, platinum folding clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "chopard",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Rose Gold",
    caseSizeMm: 43,
    categoryId: "timepieces",
    description:
      "A perpetual calendar with the rare convenience of a crown-correction system, in a rose gold case powered by the twin-barrel calibre L.U.C 82.15-L.",
    featured: false,
    features: [
      "Hand-wound calibre L.U.C 82.15-L, 65h reserve",
      "Perpetual calendar with crown correction",
      "Rose gold case, Grand Feu enamel dial",
      "Sapphire caseback",
    ],
    id: "chopard-luc-perpetual-twin",
    image: img(5),
    movement: "Manual-Wind",
    name: "L.U.C Perpetual Twin",
    price: 70000,
    ref: "161933-1001",
    specs: {
      Case: "43mm, 18k rose gold",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre L.U.C 82.15-L, hand-wound, 65h reserve",
      Strap: "Alligator, gold folding clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "chopard",
    waterResistanceM: 50,
  },

  // ── Hublot ──────────────────────────────────────────────────────────────────
  {
    caseMaterial: "Ceramic",
    caseSizeMm: 44,
    categoryId: "timepieces",
    description:
      "The Big Bang that launched the fusion concept — a ceramic case with exposed screws and a skeleton dial over the flyback calibre HUB4100.",
    featured: true,
    features: [
      "Flyback chronograph calibre HUB4100, 42h reserve",
      "Ceramic case, skeletonised dial",
      "Exposed screws, multi-layer construction",
      "100m water resistance",
    ],
    id: "hublot-big-bang-301",
    image: img(3),
    movement: "Automatic",
    name: "Big Bang 301.CI.1770.RX",
    price: 25000,
    ref: "301.CI.1770.RX",
    specs: {
      Case: "44mm, ceramic",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre HUB4100, self-winding, 42h reserve",
      Strap: "Rubber, ceramic folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "hublot",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Ceramic",
    caseSizeMm: 45,
    categoryId: "timepieces",
    description:
      "The Unico calibre in full view: a column-wheel chronograph with a horizontal date, cased in black ceramic with a skeleton dial.",
    featured: false,
    features: [
      "Calibre HUB1242 UNICO, 72h reserve",
      "Column-wheel chronograph, horizontal date",
      "Black ceramic case",
      "Skeleton dial with dual counters",
    ],
    id: "hublot-big-bang-unico",
    image: img(10),
    movement: "Automatic",
    name: "Big Bang Unico 441.CM.1170.RX",
    price: 22000,
    ref: "441.CM.1170.RX",
    specs: {
      Case: "45mm, ceramic",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre HUB1242, self-winding, 72h reserve",
      Strap: "Rubber, ceramic folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "hublot",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Ceramic",
    caseSizeMm: 45,
    categoryId: "timepieces",
    description:
      "The cleaner, dressier side of Hublot: a polished ceramic case with a satin-brushed dial and a three-hand calibre HUB1112.",
    featured: false,
    features: [
      "Calibre HUB1112, self-winding, 42h reserve",
      "Polished ceramic case",
      "Satin-finished sunray dial",
      "50m water resistance",
    ],
    id: "hublot-classic-fusion",
    image: img(1),
    movement: "Automatic",
    name: "Classic Fusion 511.CM.1170.RX",
    price: 9000,
    ref: "511.CM.1170.RX",
    specs: {
      Case: "45mm, ceramic",
      Crystal: "Sapphire",
      Movement: "Calibre HUB1112, self-winding, 42h reserve",
      Strap: "Rubber, ceramic folding clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "hublot",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Rose Gold",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "The tonneau-shaped Spirit: King Gold case, skeleton dial and the barrel-form flyback chronograph calibre HUB4700.",
    featured: false,
    features: [
      "Flyback chronograph calibre HUB4700, 50h reserve",
      "King Gold tonneau case",
      "Skeleton dial, sunray finish",
      "100m water resistance",
    ],
    id: "hublot-spirit-big-bang",
    image: img(7),
    movement: "Automatic",
    name: "Spirit of Big Bang 641.OM.1180.RX",
    price: 25000,
    ref: "641.OM.1180.RX",
    specs: {
      Case: "42mm, King Gold, tonneau",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre HUB4700, self-winding, 50h reserve",
      Strap: "Rubber, gold folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "hublot",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Titanium",
    caseSizeMm: 45,
    categoryId: "timepieces",
    description:
      "A skeleton hand-wound with a 10-day power reserve displayed like a car's odometer — a visible mechanical spectacle in titanium.",
    featured: false,
    features: [
      "Hand-wound calibre HUB1201, 10-day reserve",
      "Odometer-style power reserve display",
      "Skeleton dial, titanium case",
      "100m water resistance",
    ],
    id: "hublot-big-bang-meca-10",
    image: img(14),
    movement: "Manual-Wind",
    name: "Big Bang Meca-10 414.MX.1118.RX",
    price: 22000,
    ref: "414.MX.1118.RX",
    specs: {
      Case: "45mm, titanium",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre HUB1201, hand-wound, 10-day reserve",
      Strap: "Rubber, titanium folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "hublot",
    waterResistanceM: 100,
  },

  // ── Zenith ──────────────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 38,
    categoryId: "timepieces",
    description:
      "The 1969 El Primero reborn: a 38mm case, three-colour tri-compax sub-dials and the 1/10-second accuracy of the El Primero 3600.",
    featured: true,
    features: [
      "El Primero 3600, 1/10th-second chronograph, 60h reserve",
      "Tri-colour tri-compax sub-dials",
      "38mm case, 1969 proportions",
      "50m water resistance",
    ],
    id: "zenith-chronomaster-original",
    image: img(15),
    movement: "Automatic",
    name: "Chronomaster Original",
    price: 8000,
    ref: "03.3100.3600/69.C822",
    specs: {
      Case: "38mm, steel",
      Crystal: "Domed sapphire, both sides",
      Movement: "El Primero 3600, self-winding, 60h reserve",
      Strap: "Steel bracelet, folding clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "zenith",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 37,
    categoryId: "timepieces",
    description:
      "A faithful reissue of the original 1969 A384: a panda dial, faceted barrel case and the ladder-bracelet era's sharpest angles.",
    featured: false,
    features: [
      "El Primero 400, high-frequency 36,000 vph",
      "Lacquered panda dial",
      "Faceted barrel-shaped case",
      "Ladder-design steel bracelet",
    ],
    id: "zenith-el-primero-a384",
    image: img(11),
    movement: "Automatic",
    name: "El Primero A384 Revival",
    price: 9000,
    ref: "03.A384.400/21.C815",
    specs: {
      Case: "37mm, steel, faceted",
      Crystal: "Sapphire, both sides",
      Movement: "El Primero 400, self-winding, 50h reserve",
      Strap: "Steel bracelet, folding clasp",
      "Water Resistance": "50m / 5 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "zenith",
    waterResistanceM: 50,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A 1/10-second chronograph with a four-pointed star dial, an octagonal bezel and an integrated bracelet with a quick-release system.",
    featured: false,
    features: [
      "El Primero 3620, 1/10th-second, 60h reserve",
      "Four-pointed star (dodecagonal) dial",
      "Octagonal bezel, integrated bracelet",
      "100m water resistance",
    ],
    id: "zenith-defy-skyline",
    image: img(0),
    movement: "Automatic",
    name: "Defy Skyline",
    price: 8800,
    ref: "03.9300.3620/51.I001",
    specs: {
      Case: "41mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "El Primero 3620, self-winding, 60h reserve",
      Strap: "Steel bracelet, quick-release",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "zenith",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Titanium",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "A lightweight titanium skeleton with an openworked Elite calibre and a flying tourbillon-level view of the gear train.",
    featured: false,
    features: [
      "Elite 670 skeletonised, 50h reserve",
      "Titanium case, openworked dial",
      "Integrated rubber strap",
      "100m water resistance",
    ],
    id: "zenith-defy-classic",
    image: img(12),
    movement: "Automatic",
    name: "Defy Classic 16.9100.670/51.C927",
    price: 6000,
    ref: "16.9100.670/51.C927",
    specs: {
      Case: "41mm, titanium",
      Crystal: "Sapphire, both sides",
      Movement: "Elite 670 SK, self-winding, 50h reserve",
      Strap: "Rubber, titanium folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "zenith",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 43,
    categoryId: "timepieces",
    description:
      "A heritage aviator with a tronconic crown and a broad date aperture, powered by the 1/10-second El Primero 3620.",
    featured: false,
    features: [
      "El Primero 3620, 1/10th-second, 60h reserve",
      "Tronconic crown, oversized date",
      "Matte black dial, Super-LumiNova",
      "100m water resistance",
    ],
    id: "zenith-pilot-big-date",
    image: img(13),
    movement: "Automatic",
    name: "Pilot Big Date",
    price: 8600,
    ref: "03.4000.3625/21.I001",
    specs: {
      Case: "42.5mm, steel",
      Crystal: "Domed sapphire",
      Movement: "El Primero 3620, self-winding, 60h reserve",
      Strap: "Leather, steel folding clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "zenith",
    waterResistanceM: 100,
  },

  // ── IWC Schaffhausen ────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "The 1939 Portugieser classic: a clean dial with two stacked counters, gold-plated hands and the calibre 79350 chronograph.",
    featured: true,
    features: [
      "Calibre 79350, column-wheel chronograph, 44h reserve",
      "Two overlapping sub-dials",
      "Rail-track minute ring",
      "Alligator strap with folding clasp",
    ],
    id: "iwc-portugieser-chronograph",
    image: img(16),
    movement: "Automatic",
    name: "Portugieser Chronograph IW371446",
    price: 7700,
    ref: "IW371446",
    specs: {
      Case: "40.9mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 79350, self-winding, 44h reserve",
      Strap: "Black alligator, folding clasp",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "iwc-schaffhausen",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The aviator's daily companion: a 40mm steel case, luminous triangle at 12 and the five-day calibre 32111 with a soft-iron antimagnetic cage.",
    featured: false,
    features: [
      "Calibre 32111, 120h power reserve",
      "Soft-iron antimagnetic cage",
      "40mm case, aviation DNA",
      "100m water resistance",
    ],
    id: "iwc-pilot-mark-xx",
    image: img(13),
    movement: "Automatic",
    name: "Pilot's Watch Mark XX",
    price: 5500,
    ref: "IW328201",
    specs: {
      Case: "40mm, steel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 32111, self-winding, 120h reserve",
      Strap: "Steel bracelet, quick-change",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "iwc-schaffhausen",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "Gérald Genta's 1976 engineer returns: an integrated steel bracelet, a bezel of five screws and the in-house calibre 32111.",
    featured: false,
    features: [
      "Calibre 32111, 120h power reserve",
      "Five-screw bezel, Genta-inspired",
      "Integrated H-link bracelet",
      "Antimagnetic to 80,000 A/m",
    ],
    id: "iwc-ingenieur-40",
    image: img(6),
    movement: "Automatic",
    name: "Ingenieur Automatic 40",
    price: 12000,
    ref: "IW328901",
    specs: {
      Case: "40mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre 32111, self-winding, 120h reserve",
      Strap: "Integrated steel bracelet",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "iwc-schaffhausen",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 46,
    categoryId: "timepieces",
    description:
      "The original observation-watch: 46mm, a seven-day reserve and a crown like a fighter's throttle, finished in black with a stitched strap.",
    featured: false,
    features: [
      "Calibre 52111, 7-day power reserve",
      "46mm case, oversized crown",
      "Large Arabic numerals, luminous hands",
      "60m water resistance",
    ],
    id: "iwc-big-pilot-iw501001",
    image: img(17),
    movement: "Automatic",
    name: "Big Pilot's Watch IW501001",
    price: 15500,
    ref: "IW501001",
    specs: {
      Case: "46.2mm, steel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 52111, self-winding, 7-day reserve",
      Strap: "Black leather, steel pin buckle",
      "Water Resistance": "60m / 6 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "iwc-schaffhausen",
    waterResistanceM: 60,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The understated dress watch of the Portofino line: a slim steel case, silver-plated dial and the simple elegance of calibre 35111.",
    featured: false,
    features: [
      "Calibre 35111, self-winding, 42h reserve",
      "Silver-plated dial, Roman numerals",
      "Slim steel case, 9.2mm",
      "Alligator strap",
    ],
    id: "iwc-portofino",
    image: img(1),
    movement: "Automatic",
    name: "Portofino Automatic IW356518",
    price: 4800,
    ref: "IW356518",
    specs: {
      Case: "40mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre 35111, self-winding, 42h reserve",
      Strap: "Black alligator, pin buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "iwc-schaffhausen",
    waterResistanceM: 30,
  },

  // ── Panerai ─────────────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 44,
    categoryId: "timepieces",
    description:
      "The archetypal Luminor: a 44mm cushion case with the patented crown-protector bridge, sandwich dial and the hand-wound calibre OP XI.",
    featured: true,
    features: [
      "Hand-wound calibre OP XI, 56h reserve",
      "Patented crown-protector bridge",
      "Sandwich dial with luminous numerals",
      "300m water resistance",
    ],
    id: "panerai-luminor-marina-pam111",
    image: img(2),
    movement: "Manual-Wind",
    name: "Luminor Marina PAM00111",
    price: 7000,
    ref: "PAM00111",
    specs: {
      Case: "44mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre OP XI, hand-wound, 56h reserve",
      Strap: "Alligator, steel pin buckle",
      "Water Resistance": "300m / 30 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "panerai",
    waterResistanceM: 300,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 44,
    categoryId: "timepieces",
    description:
      "A 44mm dive tool with a unidirectional bezel and a bright blue sandwich dial, powered by the three-day calibre P.900.",
    featured: false,
    features: [
      "Calibre P.900, 72h power reserve",
      "Unidirectional rotating bezel",
      "Blue sandwich dial",
      "300m water resistance",
    ],
    id: "panerai-submersible-pam1389",
    image: img(12),
    movement: "Automatic",
    name: "Submersible QuarantaQuattro PAM01389",
    price: 8700,
    ref: "PAM01389",
    specs: {
      Case: "44mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre P.900, self-winding, 72h reserve",
      Strap: "Rubber, steel pin buckle",
      "Water Resistance": "300m / 30 ATM",
    },
    strapMaterial: "Rubber",
    subcategoryId: "panerai",
    waterResistanceM: 300,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 45,
    categoryId: "timepieces",
    description:
      "The 1936 original: a cushion case with wire lugs, a sandwich dial and the eight-day hand-wound calibre P.5000.",
    featured: false,
    features: [
      "Hand-wound calibre P.5000, 8-day reserve",
      "Cushion case with wire lugs",
      "Sandwich dial, luminous numerals",
      "100m water resistance",
    ],
    id: "panerai-radiomir-pam510",
    image: img(9),
    movement: "Manual-Wind",
    name: "Radiomir PAM00510",
    price: 6500,
    ref: "PAM00510",
    specs: {
      Case: "45mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre P.5000, hand-wound, 8-day reserve",
      Strap: "Leather, steel pin buckle",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "panerai",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 42,
    categoryId: "timepieces",
    description:
      "The slimmed-down Luminor: 42mm and just 10.7mm thin, with an off-centre small seconds and the micro-rotor calibre P.4000.",
    featured: false,
    features: [
      "Calibre P.4000 with micro-rotor, 72h reserve",
      "42mm case, 10.7mm thin",
      "Off-centre small seconds",
      "30m water resistance",
    ],
    id: "panerai-luminor-due-pam976",
    image: img(4),
    movement: "Automatic",
    name: "Luminor Due PAM00976",
    price: 9000,
    ref: "PAM00976",
    specs: {
      Case: "42mm, steel",
      Crystal: "Sapphire, both sides",
      Movement: "Calibre P.4000, self-winding, 72h reserve",
      Strap: "Alligator, steel pin buckle",
      "Water Resistance": "30m / 3 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "panerai",
    waterResistanceM: 30,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 44,
    categoryId: "timepieces",
    description:
      "A traveller's Luminor with an independent GMT hand and an AM/PM indicator at 9 o'clock, on a 24-hour rotating bezel.",
    featured: false,
    features: [
      "Calibre OP VIII GMT, 42h reserve",
      "Independent GMT hand, AM/PM indicator",
      "24-hour rotating bezel",
      "300m water resistance",
    ],
    id: "panerai-luminor-gmt-pam88",
    image: img(10),
    movement: "Automatic",
    name: "Luminor GMT PAM00088",
    price: 8500,
    ref: "PAM00088",
    specs: {
      Case: "44mm, steel",
      Crystal: "Sapphire",
      Movement: "Calibre OP VIII GMT, self-winding, 42h reserve",
      Strap: "Leather, steel pin buckle",
      "Water Resistance": "300m / 30 ATM",
    },
    strapMaterial: "Leather",
    subcategoryId: "panerai",
    waterResistanceM: 300,
  },

  // ── Rolex ───────────────────────────────────────────────────────────────────
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "The definitive dive watch since 1953: a 41mm Oystersteel case, a unidirectional ceramic bezel and the chronometer calibre 3235.",
    featured: true,
    features: [
      "Calibre 3235, 70h power reserve",
      "Unidirectional Cerachrom bezel",
      "Oystersteel case, 300m water resistance",
      "Glidelock clasp, Oyster bracelet",
    ],
    id: "rolex-submariner-126610",
    image: img(8),
    movement: "Automatic",
    name: "Submariner Date 126610LN",
    price: 9800,
    ref: "126610LN",
    specs: {
      Case: "41mm, Oystersteel",
      Crystal: "Sapphire, Cyclops date",
      Movement: "Calibre 3235, self-winding, 70h reserve",
      Strap: "Oystersteel bracelet, Glidelock clasp",
      "Water Resistance": "300m / 30 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "rolex",
    waterResistanceM: 300,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The racing chronograph, crowned with the 1963 name and now the in-house calibre 4131 with a chronometer certificate and a 72-hour reserve.",
    featured: false,
    features: [
      "Calibre 4131, chronometer, 72h reserve",
      "Tachymetric Cerachrom bezel",
      "Three-chronograph-counter dial",
      "Oystersteel bracelet",
    ],
    id: "rolex-daytona-126500",
    image: img(3),
    movement: "Automatic",
    name: "Cosmograph Daytona 126500LN",
    price: 16000,
    ref: "126500LN",
    specs: {
      Case: "40mm, Oystersteel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 4131, self-winding, 72h reserve",
      Strap: "Oystersteel bracelet, Oysterclasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "rolex",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 41,
    categoryId: "timepieces",
    description:
      "The icon of 1945: a white Rolesor case, a fluted white-gold bezel, a date with Cyclops and a Jubilee bracelet, powered by calibre 3235.",
    featured: false,
    features: [
      "Calibre 3235, 70h power reserve",
      "Fluted white-gold bezel",
      "Date with Cyclops lens",
      "Jubilee bracelet with hidden clasp",
    ],
    id: "rolex-datejust-41",
    image: img(14),
    movement: "Automatic",
    name: "Datejust 41 126334",
    price: 10000,
    ref: "126334",
    specs: {
      Case: "41mm, Oystersteel and white gold",
      Crystal: "Sapphire, Cyclops date",
      Movement: "Calibre 3235, self-winding, 70h reserve",
      Strap: "Jubilee bracelet, concealed Crownclasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "rolex",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 40,
    categoryId: "timepieces",
    description:
      "The 'Batman' GMT: a blue-and-black Cerachrom bezel, an independent 24-hour hand and calibre 3285 for tracking two time zones at once.",
    featured: false,
    features: [
      "Calibre 3285, 70h power reserve",
      "Blue and black Cerachrom bezel",
      "Independent 24-hour hand",
      "Oyster bracelet with Easylink",
    ],
    id: "rolex-gmt-master-ii-blnr",
    image: img(0),
    movement: "Automatic",
    name: "GMT-Master II 126710BLNR",
    price: 11000,
    ref: "126710BLNR",
    specs: {
      Case: "40mm, Oystersteel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 3285, self-winding, 70h reserve",
      Strap: "Oystersteel bracelet, Easylink clasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "rolex",
    waterResistanceM: 100,
  },
  {
    caseMaterial: "Steel",
    caseSizeMm: 36,
    categoryId: "timepieces",
    description:
      "Born of the 1953 Everest expedition: a 36mm case, the luminous 3-6-9 dial and calibre 3230 — the explorer's tool watch, unchanged in spirit.",
    featured: false,
    features: [
      "Calibre 3230, 70h power reserve",
      "Luminous 3-6-9 dial",
      "36mm Oystersteel case",
      "100m water resistance",
    ],
    id: "rolex-explorer-124270",
    image: img(5),
    movement: "Automatic",
    name: "Explorer 124270",
    price: 7500,
    ref: "124270",
    specs: {
      Case: "36mm, Oystersteel",
      Crystal: "Sapphire, glareproofed",
      Movement: "Calibre 3230, self-winding, 70h reserve",
      Strap: "Oystersteel bracelet, Oysterclasp",
      "Water Resistance": "100m / 10 ATM",
    },
    strapMaterial: "Steel",
    subcategoryId: "rolex",
    waterResistanceM: 100,
  },
];
